# Generated by Django 4.2.23 on 2026-06-26 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import horilla_documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Category')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Document Category',
                'verbose_name_plural': 'Document Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Maternita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('n_figlio', models.IntegerField(verbose_name='N° Figlio')),
                ('nome_figlio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Figlio')),
                ('data_comunicazione', models.DateTimeField(blank=True, null=True, verbose_name='Data Comunicazione')),
                ('data_prevista_parto', models.DateTimeField(blank=True, null=True, verbose_name='Data Prevista Parto')),
                ('sedia_maternita', models.CharField(blank=True, choices=[('SI', 'Sì'), ('NO', 'No')], max_length=10, null=True, verbose_name='Sedia Maternità')),
                ('sostituta', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sostituta')),
                ('id_sostituta', models.CharField(blank=True, help_text='badge_id del dipendente selezionato come sostituta', max_length=255, null=True, verbose_name='Badge ID Sostituta')),
                ('data_nascita', models.DateTimeField(blank=True, null=True, verbose_name='Data Nascita')),
                ('data_rientro', models.DateTimeField(blank=True, null=True, verbose_name='Data Rientro')),
                ('negozio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Negozio')),
                ('documento', models.FileField(blank=True, null=True, upload_to=horilla_documents.models.maternita_upload_path, verbose_name='Documento comunicazione')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maternita_set', to='employee.employee', verbose_name='Dipendente')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Maternità',
                'verbose_name_plural': 'Maternità',
                'ordering': ['employee_id', 'n_figlio'],
                'unique_together': {('employee_id', 'n_figlio')},
            },
        ),
        migrations.CreateModel(
            name='DocumentSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('name', models.CharField(max_length=200, verbose_name='Sub Category')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='horilla_documents.documentcategory', verbose_name='Category')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Document Sub Category',
                'verbose_name_plural': 'Document Sub Categories',
                'ordering': ['name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('format', models.CharField(choices=[('any', 'Any'), ('pdf', 'PDF'), ('txt', 'TXT'), ('docx', 'DOCX'), ('xlsx', 'XLSX'), ('jpg', 'JPG'), ('png', 'PNG'), ('jpeg', 'JPEG')], max_length=10, verbose_name='Format')),
                ('max_size', models.IntegerField(blank=True, null=True, verbose_name='Max size (In MB)')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee_id', models.ManyToManyField(to='employee.employee', verbose_name='Employees')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Document Request',
                'verbose_name_plural': 'Document Requests',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=horilla_documents.models.document_upload_path, verbose_name='Document')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=10, verbose_name='Status')),
                ('reject_reason', models.TextField(blank=True, max_length=255, null=True, verbose_name='Reject Reason')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Data Documento')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data Inizio')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Data Fine')),
                ('upload_date', models.DateTimeField(blank=True, null=True, verbose_name='Data Caricamento')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('notify_before', models.IntegerField(default=1, null=True, verbose_name='Notifica Prima (giorni)')),
                ('beneficiario', models.CharField(blank=True, max_length=255, null=True, verbose_name='Beneficiario')),
                ('is_digital_asset', models.BooleanField(default=False, verbose_name='Is Digital Asset')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='horilla_documents.documentcategory', verbose_name='Categoria')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('document_request_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='horilla_documents.documentrequest')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee', verbose_name='Employee')),
                ('maternita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='horilla_documents.maternita', verbose_name='Maternità')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='horilla_documents.documentsubcategory', verbose_name='Sottocategoria')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
