"""
component_urls.py

This module is used to bind the urls related to payslip and its pay-heads methods
"""

from django.urls import path

from payroll.models.models import Allowance, Deduction
from payroll.views import component_views

urlpatterns = [
    path(
        "allowances-deductions-tab/<int:emp_id>",
        component_views.allowances_deductions_tab,
        name="allowances-deductions-tab",
    ),
    path("create-allowance", component_views.create_allowance, name="create-allowance"),
    path("view-allowance/", component_views.view_allowance, name="view-allowance"),
    path(
        "single-allowance-view/<int:allowance_id>",
        component_views.view_single_allowance,
        name="single-allowance-view",
    ),
    path("filter-allowance", component_views.filter_allowance, name="filter-allowance"),
    path(
        "update-allowance/<int:allowance_id>/",
        component_views.update_allowance,
        name="update-allowance",
        kwargs={"model": Allowance},
    ),
    path(
        "delete-allowance/<int:allowance_id>/",
        component_views.delete_allowance,
        name="delete-allowance",
    ),
    path(
        "delete-employee-allowance/<int:allowance_id>/",
        component_views.delete_allowance,
        name="delete-employee-allowance",
    ),
    path("create-deduction", component_views.create_deduction, name="create-deduction"),
    path("view-deduction/", component_views.view_deduction, name="view-deduction"),
    path(
        "single-deduction-view/<int:deduction_id>",
        component_views.view_single_deduction,
        name="single-deduction-view",
    ),
    path("filter-deduction", component_views.filter_deduction, name="filter-deduction"),
    path(
        "update-deduction/<int:deduction_id>/",
        component_views.update_deduction,
        name="update-deduction",
        kwargs={"model": Deduction},
    ),
    path(
        "delete-deduction/<int:deduction_id>/",
        component_views.delete_deduction,
        name="delete-deduction",
    ),
    path(
        "delete-deduction/<int:deduction_id>/<int:emp_id>/",
        component_views.delete_deduction,
        name="delete-deduction",
    ),
    path("create-payslip", component_views.create_payslip, name="create-payslip"),
    path(
        "check-contract-start-date",
        component_views.check_contract_start_date,
        name="check-contract-start-date",
    ),
    path("generate-payslip", component_views.generate_payslip, name="generate-payslip"),
    path(
        "validate-start-date",
        component_views.validate_start_date,
        name="validate-start-date",
    ),
    path("filter-payslip", component_views.filter_payslip, name="filter-payslip"),
    path(
        "payslip-info-export",
        component_views.payslip_export,
        name="payslip-info-export",
    ),
    path(
        "view-individual-payslip/<int:employee_id>/<str:start_date>/<str:end_date>/",
        component_views.view_individual_payslip,
        name="view-individual-payslip",
    ),
    path("view-payslip/", component_views.view_payslip, name="view-payslip"),
    path(
        "import-payslip-presenze/",
        component_views.import_payslip_presenze,
        name="import-payslip-presenze",
    ),
    path(
        "delete-payslip-presenze/",
        component_views.delete_payslip_presenze,
        name="delete-payslip-presenze",
    ),
    path(
        "import-payslip-corpo/",
        component_views.import_payslip_corpo,
        name="import-payslip-corpo",
    ),
    path(
        "delete-payslip-corpo/",
        component_views.delete_payslip_corpo,
        name="delete-payslip-corpo",
    ),
    path(
        "import-payslip-importi/",
        component_views.import_payslip_importi,
        name="import-payslip-importi",
    ),
    path(
        "delete-payslip-importi/",
        component_views.delete_payslip_importi,
        name="delete-payslip-importi",
    ),
    path(
        "presenze-by-lavoratore/",
        component_views.presenze_by_lavoratore,
        name="presenze-by-lavoratore",
    ),
    path(
        "presenze-lavoratore-rows/",
        component_views.presenze_lavoratore_rows,
        name="presenze-lavoratore-rows",
    ),
    path(
        "controllo-cedolini/",
        component_views.controllo_cedolini,
        name="controllo-cedolini",
    ),
    path(
        "controllo-cedolini/presenze/",
        component_views.controllo_cedolini_presenze,
        name="controllo-cedolini-presenze",
    ),
    path(
        "controllo-cedolini/importi/",
        component_views.controllo_cedolini_importi,
        name="controllo-cedolini-importi",
    ),
    path(
        "controllo-cedolini/acconti/",
        component_views.controllo_cedolini_acconti,
        name="controllo-cedolini-acconti",
    ),
    path(
        "controllo-cedolini/malattie/",
        component_views.controllo_cedolini_malattie,
        name="controllo-cedolini-malattie",
    ),
    path(
        "export-malattie-excel/",
        component_views.export_malattie_excel,
        name="export-malattie-excel",
    ),
    path(
        "export-malattie-docx/",
        component_views.export_malattie_docx,
        name="export-malattie-docx",
    ),
    path(
        "export-acconti-excel/",
        component_views.export_acconti_excel,
        name="export-acconti-excel",
    ),
    path(
        "export-acconti-docx/",
        component_views.export_acconti_docx,
        name="export-acconti-docx",
    ),
    path(
        "toggle-dizionario-attivo/<int:mapping_id>/",
        component_views.toggle_dizionario_attivo,
        name="toggle-dizionario-attivo",
    ),
    path(
        "aggiungi-dizionario/",
        component_views.aggiungi_dizionario,
        name="aggiungi-dizionario",
    ),
    path(
        "elimina-dizionario/<int:mapping_id>/",
        component_views.elimina_dizionario,
        name="elimina-dizionario",
    ),
    path(
        "toggle-regola-controllo-attiva/<int:regola_id>/",
        component_views.toggle_regola_controllo_attiva,
        name="toggle-regola-controllo-attiva",
    ),
    path(
        "aggiungi-regola-controllo/",
        component_views.aggiungi_regola_controllo,
        name="aggiungi-regola-controllo",
    ),
    path(
        "elimina-regola-controllo/<int:regola_id>/",
        component_views.elimina_regola_controllo,
        name="elimina-regola-controllo",
    ),
    path(
        "toggle-regola-destinazione-attiva/<int:destinazione_id>/",
        component_views.toggle_regola_destinazione_attiva,
        name="toggle-regola-destinazione-attiva",
    ),
    path(
        "aggiungi-regola-destinazione/<int:regola_id>/",
        component_views.aggiungi_regola_destinazione,
        name="aggiungi-regola-destinazione",
    ),
    path(
        "elimina-regola-destinazione/<int:destinazione_id>/",
        component_views.elimina_regola_destinazione,
        name="elimina-regola-destinazione",
    ),
    path(
        "export-controllo-excel/",
        component_views.export_controllo_excel,
        name="export-controllo-excel",
    ),
    path(
        "export-controllo-docx/",
        component_views.export_controllo_docx,
        name="export-controllo-docx",
    ),
    path(
        "hx-create-allowance",
        component_views.hx_create_allowance,
        name="hx-create-allowance",
    ),
    path("send-slip", component_views.send_slip, name="send-slip"),
    path("add-bonus/", component_views.add_bonus, name="add-bonus"),
    path(
        "add-payslip-deduction/",
        component_views.add_deduction,
        name="add-payslip-deduction",
    ),
    path("view-loan/", component_views.view_loans, name="view-loan"),
    path("create-loan/", component_views.create_loan, name="create-loan"),
    path(
        "view-installments/",
        component_views.view_installments,
        name="view-installments",
    ),
    path(
        "edit-installment-amount/",
        component_views.edit_installment_amount,
        name="edit-installment-amount",
    ),
    path("delete-loan/", component_views.delete_loan, name="delete-loan"),
    path("search-loan/", component_views.search_loan, name="search-loan"),
    path(
        "asset-fine/",
        component_views.asset_fine,
        name="asset-fine",
    ),
    path(
        "view-reimbursement/",
        component_views.view_reimbursement,
        name="view-reimbursement",
    ),
    path(
        "create-reimbursement",
        component_views.create_reimbursement,
        name="create-reimbursement",
    ),
    path(
        "search-reimbursement",
        component_views.search_reimbursement,
        name="search-reimbursement",
    ),
    path(
        "get-assigned-leaves/",
        component_views.get_assigned_leaves,
        name="get-assigned-leaves",
    ),
    path(
        "approve-reimbursements",
        component_views.approve_reimbursements,
        name="approve-reimbursements",
    ),
    path(
        "delete-reimbursements",
        component_views.delete_reimbursements,
        name="delete-reimbursement",
    ),
    path(
        "reimbursement-individual-view/<int:instance_id>/",
        component_views.reimbursement_individual_view,
        name="reimbursement-individual-view",
    ),
    path(
        "reimbursement-attachements/<int:instance_id>/",
        component_views.reimbursement_attachments,
        name="reimbursement-attachments",
    ),
    path(
        "delete-attachments/<int:_reimbursement_id>/",
        component_views.delete_attachments,
        name="delete-attachments",
    ),
    path(
        "get-contribution-report",
        component_views.get_contribution_report,
        name="get-contribution-report",
    ),
    path(
        "payslip-detailed-export",
        component_views.payslip_detailed_export,
        name="payslip-detailed-export",
    ),
]
